### ISSUE TITLE
Working on a Directus source plugin

### ISSUE THREAD

**Issue by lexoyo** [stackbithq/sourcebit#31]
Hello,

I'm wondering if a [Directus](https://directus.io/) source plugin for sourcebit is a good thing to invest time on

First, I am wondering if sourcebit is still alive - it doesn't seem vibrant at all but the JAMStack ecosystem is desperately needing such a "normalizing" piece of software. Maybe there is a better option? I didn't really find one. Maybe there is a reason for it to have small amount of contributions? Maybe it just works?

The context: I'm working on [Silex](https://www.silex.me), planing the next major version in which the drag and drop builder will display dynamic data coming from [Directus](https://directus.io/) and why not from other sources thanks to sourcebit

Something like webflow's CMS field binding:

![9Q79JD](https://user-images.githubusercontent.com/715377/184536091-a636a037-0be6-49df-858b-db8e3422d24f.gif)

Thank you in advance for any piece of info about sourcebit passed and future history/community

**Comment by seancdavis** [comment]
Hi @lexoyo! Thanks for the question.

As of now, we are not currently planning to continue development on Sourcebit. We are supporting it in a limited capacity at this time.

We developed [Contentlayer](https://www.contentlayer.dev/) as the next iteration of reading and normalizing content from a number of sources. Contentlayer is solid for file-based content only right now, with support for Conetntful and others coming soon.

At this point, we're recommending that developers use content providers' SDKs directly, as we look to eventually deprecate Sourcebit and introduce more sources into Contentlayer.

**Comment by lexoyo** [comment]
Thank you so much for your answer! See you on Contentlayer then (great name btw)
